<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="en-gb" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<title>FrenchScene.Net Community &bull; Index page</title>

<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:      
	
	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to.:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	
	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/prosilver/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/prosilver/template/forum_fn.js"></script>

<link href="./styles/prosilver/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?sid=12fdbe2b86e3f6c6b46792148a6c8a67&amp;id=1&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/prosilver/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/prosilver/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/prosilver/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />


</head>

<body id="phpbb" class="section-index ltr">

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner"><span class="corners-top"><span></span></span>

<div style="height: 340px;">
			<div id="site-description">
				<p style="display: none;"><a href="#start_here">Skip to content</a></p>
			</div>

        
        </div>

			<span class="corners-bottom"><span></span></span></div>
		</div>

		<div class="navbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<ul class="linklist navlinks">
				<li class="icon-home"><a href="./index.php" accesskey="h">Board index</a> </li>

				<li class="rightside"><a href="#" onclick="fontsizeup(); return false;" onkeypress="fontsizeup(); return false;" class="fontsize" title="Change font size">Change font size</a></li>

							</ul>

			
			<ul class="linklist rightside">
				<li class="icon-faq"><a href="./faq.php" title="Frequently Asked Questions">FAQ</a></li>
							</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>

	</div>

	<a name="start_here"></a>
	<div id="page-body">
		
		 
<p class="right rightside">Last visit was: Sat Dec 12, 2009 5:24 pm</p>
<p>It is currently Sat Dec 12, 2009 5:24 pm</p>		<div class="forabg">
			<div class="inner"><span class="corners-top"><span></span></span>
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=3">FrenchScene.Net Community :: Passion For Music</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
			<li class="row">
			<dl class="icon" style="background-image: url(./styles/prosilver/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No new posts">
										<a href="./viewforum.php?f=4" class="forumtitle">Building FrenchScene.Net :: Be a part of it</a><br />
					Here you can post your ideas or offer your help for this great project!									</dt>
									<dd class="topics">7839 <dfn>Topics</dfn></dd>
					<dd class="posts">15829 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Woompohop						<a href="./viewtopic.php?f=4&amp;p=27107#p27107"><img src="./styles/prosilver/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Sat Dec 12, 2009 5:24 pm</span>
					</dd>
							</dl>
		</li>
			<li class="row">
			<dl class="icon" style="background-image: url(./styles/prosilver/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No new posts">
										<a href="./viewforum.php?f=5" class="forumtitle">French Artists</a><br />
					Discuss French artists here!									</dt>
									<dd class="topics">2531 <dfn>Topics</dfn></dd>
					<dd class="posts">4824 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by standelathe						<a href="./viewtopic.php?f=5&amp;p=27038#p27038"><img src="./styles/prosilver/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Sat Dec 12, 2009 3:28 pm</span>
					</dd>
							</dl>
		</li>
			<li class="row">
			<dl class="icon" style="background-image: url(./styles/prosilver/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No new posts">
										<a href="./viewforum.php?f=6" class="forumtitle">French Songs</a><br />
					Don't know the name of a French song? Want to request a lyric translation? Or you just want to let us hear that great song you've just stumbled upon, here's where to do it!									</dt>
									<dd class="topics">4628 <dfn>Topics</dfn></dd>
					<dd class="posts">6448 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Woompohop						<a href="./viewtopic.php?f=6&amp;p=27106#p27106"><img src="./styles/prosilver/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Sat Dec 12, 2009 5:23 pm</span>
					</dd>
							</dl>
		</li>
				</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>
	<h3>Who is online</h3>	<p>In total there are <strong>5</strong> users online :: 3 registered, 0 hidden and 2 guests (based on users active over the past 5 minutes)<br />Most users ever online was <strong>32</strong> on Fri Aug 14, 2009 1:34 am<br /> <br />Registered users: <span style="color: #9E8DA7;" class="username-coloured">Alexa [Bot]</span>, JozefBratan, Woompohop	<br /><em>Legend: <a style="color:#AA0000" href="./memberlist.php?mode=group&amp;g=5">Administrators</a>, <a style="color:#00AA00" href="./memberlist.php?mode=group&amp;g=4">Global moderators</a></em></p>
	<h3>Statistics</h3>
	<p>Total posts <strong>27042</strong> &bull; Total topics <strong>14952</strong> &bull; Total members <strong>1960</strong> &bull; Our newest member <strong>Banonouse</strong></p>
</div>

<div id="page-footer">

	<div class="navbar">
		<div class="inner"><span class="corners-top"><span></span></span>

		<ul class="linklist">
			<li class="icon-home"><a href="./index.php" accesskey="h">Board index</a></li>
							<li class="rightside"><a href="./memberlist.php?mode=leaders">The team</a> &bull; All times are UTC </li>
		</ul>

		<span class="corners-bottom"><span></span></span></div>
	</div>
	
<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	<div class="copyright">Powered by <a href="http://www.phpbb.com/">phpBB</a> &copy; 2000, 2002, 2005, 2007 phpBB Group
			</div>
</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	</div>

</body>
</html>